### ISSUE TITLE
ngTablePagination directive does not work (demo28.html)

### ISSUE THREAD

**Issue by ppawel** [esvit/ng-table#286]
I get:

```
TypeError: Cannot call method '$on' of null
    at link (file:///home/ppawel/work/ng-table/ng-table.js:694:48)
    at l (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:47:124)
    at f (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:41:361)
    at l (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:47:64)
    at f (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:41:361)
    at f (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:41:378)
    at file:///home/ppawel/work/ng-table/examples/js/angular.min.js:40:434
    at file:///home/ppawel/work/ng-table/examples/js/angular.min.js:17:364
    at h.$eval (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:105:313)
    at h.$apply (file:///home/ppawel/work/ng-table/examples/js/angular.min.js:106:48)
```

**Comment by rliebi** [comment]
I think this issue is not addressed yet. Having the same issue.

>TypeError: Cannot read property 'settings' of undefined
    at app.directive.link (http://localhost:5000/bower_components/ng-table/dist/ng-table.js:945:29)
    at http://localhost:5000/bower_components/angular/angular.js:8305:44
    at invokeLinkFn (http://localhost:5000/bower_components/angular/angular.js:8311:9)
    at nodeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7820:11)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7221:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7225:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7225:13)
    at compositeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7225:13)
    at nodeLinkFn (http://localhost:5000/bower_components/angular/angular.js:7815:24)
    at delayedNodeLinkFn (http://localhost:5000/bower_components/angular/angular.js:8068:11) <div ng-table-pagination="ngTableParams" template-url="'ng-table/pager.html'" class="ng-isolate-scope">

**Comment by Alexey79** [comment]
Hi guys,

I faced with the same issue and tried to aplly approach was described above by **flemse** Unfortunatelly I had two different behaviours so i decided to combine both solutions into one.

var isScope = function(value) {
    return (value && value.$evalAsync && value.$watch);
};

var generatePagesArray = function() {
    $scope.pages = scope.params.generatePagesArray(scope.params.page(), scope.params.total(), scope.params.count());
}

var watchRegister = $scope.$watch('params.settings().$scope', function (newValue, oldValue) {
    if (isScope(newValue)) {
        if (isScope(oldValue)) {
            generatePagesArray();
        }
        newValue.$on('ngTableAfterReloadData', generatePagesArray, true);
        watchRegister();
    }
});

**Comment by christianacca** [comment]
Try 0.8.3 as this has entirely reworked when the paging buttons get regenerated.
