### ISSUE TITLE
Error: settings.$scope.$emit is not a function

### ISSUE THREAD

**Issue by acoard** [esvit/ng-table#297]
Hey there, just wanted to start off by saying how much I appreciate the project and the work that's been going into it.

Anyways, I seem to be having a really weird error.  Basically, I can run `$scope.tableParams.reload()` twice with no problem, but on the third execution, and every following one, I get the following error:

`TypeError: Cannot set property '$data' of null at [removed]/ng-table.js:411:55`

I believe this is all the relevant code, but if anything is missing let me know:

    $scope.lookupAddress = function(address){		
		var url = 'https://blockchain.info/multiaddr?cors=true&active='+address;
		$scope.loading = true;
		$scope.clearTableData();
		$http.get(url).success(function(data){
			$scope.loading = false;
			$scope.loaded = true;
			$scope.loadError = false;
			glob = data;

			//Removed code that processes the response. 

			};
			//Enables new data to be loaded, e.g. on a new address.
			//Pretty sure it's not working right now.
			if ($scope.tableParams){
				$scope.tableParams.reload();
			} 
			data = transactions; //this data var is what is called by the tables. Unsure if can remove.
			$scope.tableParams = new ngTableParams({
		        page: 1,            
		        count: 5,           // items per page
		        sorting: {
		        	Date: 'desc' 
		        }
		    }, {
		        total: transactions.length, 
		        getData: function($defer, params) {
		        	data = transactions;
		            var orderedData = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;
		            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
		            
		        }
		    });
		}).
		error(function(data){
			$scope.loadError = true;
		});
	}

	$scope.clearTableData = function(){
		transactions = [];
		$scope.output = {}
		if ($scope.tableParams){
				$scope.tableParams.reload();
		} 
	}

**Comment by MatthewVita** [comment]
Bumping this thread to let all know that @hasi 's workaround is the only one that worked for me.

**Comment by nick250386** [comment]
I have tried all the solutions suggested here, but none of them helped me in fixing my issue.
Any inputs on this are greatly appreciated.
For the issue please visit the link: 
http://stackoverflow.com/questions/28081205/ngtable-not-loading-data

**Comment by nick250386** [comment]
Anybody, any suggestions or anything on this issue? Is anybody tracking this thread?

**Comment by OracPrime** [comment]
This won't help directly, but my solution was to ditch angular (particularly given the roadmap announced recently) and use knockout.  I have to say it has been much less painful.

**Comment by nick250386** [comment]
I don't have an option to ditch Angular. This needs to be done using AngularJS only. I have tried many posts and suggestions but none seem to work.

**Comment by joseym** [comment]
@nick250386 - since causes of the problem can differ, maybe you'd have better luck duplicating your issue in jsfiddle so we can look at it.

I agree that dropping angular completely over a table module is unlikely to be a solution for many; apps may be pretty heavily built out and on their way to completion.

**Comment by RamonBeast** [comment]
I too have tried all possible hacks and none works.
Sometimes (1 out of 8) the table is updated correctly when calling reload(), the other 7 times I keep getting:

TypeError: undefined is not a function over:
settings.$scope.$emit('ngTableAfterReloadData');

I'm currently using v0.4.3, any suggestion on how to reload the table upon data change?

**Comment by Evilcry** [comment]
I've the same issue, none of the hacks tried around here works. 
Only some reload works correctly.

Table is not usable at all.

**Comment by OracPrime** [comment]
Have you tried running in Chrome, inside dev tools, with "stop on unhandled exceptions" turned on, and checking exactly where the attempted function call is?  It may not be where you think it is...

**Comment by RamonBeast** [comment]
Thank you @OracPrime this is the result of the exception:

<exception>: TypeError: undefined is not a function
message: "undefined is not a function"
stack: "TypeError: undefined is not a function
at http://localhost:8000/js/libs/angular/ng-table.min.js:455:33
at l.promise.then.J (http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:101:96)    
at http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:102:259
at h.$get.h.$eval (http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:113:32)
at h.$get.h.$digest (http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:110:117)
at h.$get.h.$apply (http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:113:362)
at HTMLDivElement.<anonymous> (http://localhost:8000/js/libs/angular/angular-1.2.28.min.js:195:229)
at HTMLDivElement.x.event.dispatch (http://localhost:8000/js/libs/jquery-2.0.2.min.js:4:9843)
at HTMLDivElement.x.event.add.y.handle (http://localhost:8000/js/libs/jquery-2.0.2.min.js:4:6633)"

Line 455 is:
- settings.$scope.$emit('ngTableAfterReloadData');

Problem is: I'm unable to refresh the table when data changes, I've got the same problem of @Evilcry, sometimes it works some (most of) other times it doesn't. This is my code:

$scope.tableParams = new ngTableParams({
                        page: 1,
                        count: 25,
                        filter: { },
                        sorting: { "date": "desc" } }, {
                        filterDelay: 200,
                        counts: [],
                        total: data.length,
                        getData: function($defer, params) {
                            $defer.resolve(data.slice((params.page() - 1) * params.count(), params.page() * params.count()));
                        },
                        $scope: { $data: {} }
                    });

When data changes I simply issue a:
$scope.tableParams.reload();

**Comment by nick250386** [comment]
Did anybody get a chance to look into this? I have checked so many results on Google on this, and at many places, people are facing the same issue. In a scenario, there were 3 tables to be loaded, which I was able to do without any issue. In my problematic case, the first table is getting loaded without any issue. Based on the data present in the first row of the table, data needs to be loaded in the second table. I am able to get the new data for the second table, but this data is not getting rendered. I have tried all the solutions present over the internet, but none seems to work. For reference you can refer to the details of my case present at: 

http://stackoverflow.com/questions/28081205/ngtable-not-loading-data

Any ideas are welcome on this topic.

**Comment by nick250386** [comment]
Whenever, I am trying to reload the table (inside a watcher) after getting the requisite data, I get the error:
TypeError: Cannot set property '$data' of null
I further investigated the issue. This is what I found:
Before, when there is not data for the table:
{"data":[],"$params":{"page":1,"count":10,"filter":{"location":"","country":"","region":""},"sorting":{"location":"asc"},"group":{},"groupBy":null},"filterBuffer":{}}
After the watch runs, the concerned variable is loaded with data (this is confirmed), but the table params remain unchanged:
{"data":[],"$params":{"page":1,"count":10,"filter":{"location":"","country":"","region":""},"sorting":{"location":"asc"},"group":{},"groupBy":null},"filterBuffer":{}}

Any ideas why this is happening

**Comment by nick250386** [comment]
I have updated my code based on the changes I made to my previous comment. Feel free to ask any questions.
http://stackoverflow.com/questions/28081205/ngtable-not-loading-data

**Comment by cscrum** [comment]
OK..I got this to work with a combination of the above solutions plus one more thing. I used both the hasi fix of 

$scope.tableParams.settings().$scope = $scope; to get rid of the error 

and from joseym:

$scope.$watch("mygriddatavar", function (n, o) {
    $timeout(function(){ $scope.tableParams.reload(); });
  }); 

HOWEVER, I had to use two separate controllers. My application performs a search and I list the results in the table. That $http call was made in one controller, the results returned and the JSON response was stored in $scope.mygriddatavar. I created my tableParams in a separate controller and added the watch from above also in this controller. I'm not sure why this works, but I tried all in the same controller and it never worked. It was only after creating a separate controller for the table that it worked. So it looks something like:

.controller('mainController',['$scope','$route', '$animate', '$http'','ngTableParams', function($scope,$route, $animate,$http,ngTableParams) {
...blah...blah...
  $scope.searchFunc = function(){
                         var getsearchres = {
                                        url: mysearchapi,
                                        method: 'post',
                                        data : somedata
                   
                            };
                            $http(getsearchres )
                                      .success(function(data, status, headers, config) {
 
                                            $scope.mygriddatavar= data;
    
              
                                  })
                                  .error(function(data, status, headers, config) {
              
                                           $scope.alert = 'There was a network error. Try again later.';
              
                                    })
}
}])
.controller('searchControl', function($scope,$http, $filter, $timeout, ngTableParams) {

$scope.$watch('mygriddatavar', function(n,o){
                    if($scope.tableParams){
                      $timeout(function(){ $scope.tableParams.reload(); });
                     }
                }
             );

    $scope.tableParams = new ngTableParams({
        page: 1,            // show first page
        count: 10,          // count per page
        filter: {
            //Internal_ID: ''       // initial filter
        },
        sorting: {
            Internal_ID: 'asc'     // initial sorting
        }
    }, {
        total: $scope.mygriddatavar.length, // length of data
        getData: function($defer, params) {
            data = $scope.mygriddatavar;
            //use build-in angular filter
            var filteredData = params.filter() ?
                    $filter('filter')(data, params.filter()) :
                    data;
            var orderedData = params.sorting() ?
                    $filter('orderBy')(filteredData, params.orderBy()) :
                    filteredData;

            params.total(orderedData.length); // set total for recalc pagination
            $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
        },
        $scope: { $data: {} }
    });
    
    $scope.tableParams.settings().$scope = $scope;
})

**Comment by joseym** [comment]
I really think these difficulties could be more easily resolved with PROPER
API DOCUMENTATION rather than having to sift thru random code examples and
hoping for the best ...







*Josey Phone: 918.926.6678 | Gtalk: me@joseymorton.com <me@joseymorton.com>
Twitter: @joseym <http://www.twitter.com/joseym> LinkedIn: Josey Morton
<http://www.linkedin.com/profile/view?id=59813483> Github: joseym
<http://www.github.com/joseym> Blog: Tumblr <http://tumblr.joseymorton.com>*

**Comment by gitnik** [comment]
:+1: for a bug fix

**Comment by MatthewVita** [comment]
@joseym do you think we can use this code as the basis for documenting the workaround until there's a bug fix in place? https://github.com/esvit/ng-table/blob/master/src/scripts/04-controller.js#L23-L30 (L30 is, in my opinion, the current workaround)

**Comment by MatthewVita** [comment]
is this truly `closed`?  :-P

I'm more than happy to document the workaround as the interim "solution" as mentioned in my last comment, but even then the issue should still remain open.

**Comment by gitnik** [comment]
Why are closing all These Open and unresolved issues?

**Comment by iyel** [comment]
give a precise description mentionning angular version, ng-table version.

give a way to reproduce your issue, the best would be with a running example, you can use plunkr. Note if you want to mimic ajax loading behaviour you can use $timeout angular service or $httpBackend.

**Comment by MatthewVita** [comment]
@iyel I can take this on over the weekend when I have some time. I feel that 2 plunkers would be best: 1 for showing the error (thus formally isolating it*) and 1 for showing the current workaround. I will then send a small PR for the README** to have a "Known Issues" area, with a reference to the plunkers.

* this will allow this issue to be closed and a more specific issue to be opened that can focus on the specific issue and fixing it.

** Thanks for updating the readme with contrib guidelines... pretty much essential for bigger projects!

**Comment by MatthewVita** [comment]
All,

I'm attempting to reproduce the issue in this Plunker:
http://plnkr.co/edit/q8DJJF?p=preview (try to type in user ids 1, 2, 3, etc)

However, I'm not seeing the error anymore. I've tried this out with:
- Angular 1.3 + ngTable 0.3.0
- Angular 1.2 + ngTable 0.3.0
- Angular 1.3 + ngTable 0.5.0
- Angular 1.2 + ngTable 0.5.0

@hasi's solution worked for way back when, but I switched jobs since then and can't remember what the code looked like before I implemented the workaround.

I've tried to keep the Plunker as close to @acoard's controller as possible (based on his few iterations of it, that is).

Can I get some help on reproducing the issue within this Plunker?

**Comment by feelingweird** [comment]
Hi All,
I just encountered this problem on a project i inherited. Someone updated to the latest angular (1.4.*) and we were having some ngTable issues so i updated that to 1.0.0 beta and saw the error. 

it seems as though the scope is 'malformed' within the ngTable. I tried a bunch of fixes mentioned above apart from 

`$scope.tableparams.settings().$scope = $scope`

What worked for me was setting up the `$scope` for the table params on creation (i've never used this plugin before so i don't know the inner workings of the plugin or how it should be correctly used)

So our code looks something like this (this was taken from user acoard's post above)
```

$scope.tableParams = new ngTableParams({
    page: 1,            
    count: 5,           // items per page
    sorting: {
        Date: 'desc' 
    }
}, {
    total: $scope.transactions.length, 
    getData: function($defer, params) {
        var data = $scope.transactions;
        var orderedData = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;
        $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));

    },
    $scope: { $data: {} }
})
```

in our code, simply replacing 
` $scope: { $data: {} }`

with 
`$scope: $scope`
OR 
`$scope: $scope.new()`

fixed the issue. 

So in my case the lines look more like 
```
$scope.$data = {};
...
$scope.tableParams = new ngTableParams({
    page: 1,            
    count: 5,           // items per page
    sorting: {
        Date: 'desc' 
    }
}, {
    total: $scope.transactions.length, 
    getData: function($defer, params) {
        var data = $scope.transactions;
        var orderedData = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;
        $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));

    },
    $scope: $scope
})
```

so I added the `$data` to the local scope as i don't think we need an isolated scope or child scope and everything works.

hope this helps. 

cheers
kle

**Comment by draggie** [comment]
One simple modification and everything works just fine - 
`var x = function(){};
         if( (typeof newParams.reload) == (typeof x))
         newParams.reload();
`
As i checked it with console.log(), if You have multiple controllers it causes some issue when Ng-Table tries to reload object before its NgTableParams object. After this modification code works with no error.

**Comment by phienan** [comment]
Most of suggestions above are either bypassing the error and not addressing the real issue.

I run into this issue exactly at the 3rd time.  Data is in response, and the error prevented it from binding.

To replicate this issue, just create a simple search and use ng-Table to display the results.  I certainly you will run into this error after your 3rd search.  If you don't, please share your method. Thank you.
