### ISSUE TITLE
Moving pagination buttons

### ISSUE THREAD

**Issue by stefaneng** [esvit/ng-table#362]
I am trying to move the pagination buttons to a different part of my page, so I was following this example https://github.com/esvit/ng-table/blob/master/examples/demo28.html#L28

So I copied the 'pager.html' template into partials/pager.html and added
```
 <div ng-table-pagination="tableParams" template-url="'partials/pager.html'"></div>
```
to my html. When I load the page I get the error:
```
TypeError: Cannot read property '$on' of null
    at link (http://localhost:8000/bower_components/ng-table/ng-table.js:690:47)
    at http://localhost:8000/bower_components/angular/angular.js:7035:44
    at nodeLinkFn (http://localhost:8000/bower_components/angular/angular.js:6633:13)
    at compositeLinkFn (http://localhost:8000/bower_components/angular/angular.js:6028:13)
    at compositeLinkFn (http://localhost:8000/bower_components/angular/angular.js:6031:13)
    at nodeLinkFn (http://localhost:8000/bower_components/angular/angular.js:6627:24)
    at compositeLinkFn (http://localhost:8000/bower_components/angular/angular.js:6028:13)
    at publicLinkFn (http://localhost:8000/bower_components/angular/angular.js:5923:30)
    at http://localhost:8000/bower_components/angular/angular.js:1415:27
    at Scope.$eval (http://localhost:8000/bower_components/angular/angular.js:12556:28) <div ng-table-pagination="tableParams" template-url="'partials/pager.html'" class="ng-isolate-scope">
```

**Comment by hippiemine** [comment]
@tigrang it's worked,thanks.
