### ISSUE TITLE
TypeError: t.slice is not a function (caused by "undefined")

### ISSUE THREAD

**Issue by emrealparslan93** [esvit/ng-table#976]
Hello, I'm facing with this issue in one page which contains table that uses ng-table.

Here is console log: 
`TypeError: t.slice is not a function (caused by "undefined")
    at o (https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js:1:14033)
    at s (https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js:1:14326)
    at e (https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js:1:16847)
    at l.reload (https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js:1:21598)
    at https://unpkg.com/ng-table@2.0.2/bundles/ng-table.min.js:1:6817
    at Scope.$digest (http://localhost:3000/lib/angular/angular.js:17286:23)
    at Scope.$apply (http://localhost:3000/lib/angular/angular.js:17552:24)
    at done (http://localhost:3000/lib/angular/angular.js:11697:47)
    at completeRequest (http://localhost:3000/lib/angular/angular.js:11903:7)
    at XMLHttpRequest.requestLoaded (http://localhost:3000/lib/angular/angular.js:11836:9) undefined`

Can you help me with this error?
Thanks.

**Comment by emrealparslan93** [comment]
Okay, I found my mistake. I was trying to create table with null dataset.
